### ISSUE TITLE
Correção - LAB-01

### ISSUE THREAD

**Issue by fsantanna-uerj** [jaimelay/LP1#1]
Incluir imagens com a execução dos exercícios.

**Comment by jaimelay** [comment]
Adicionei as imagens em .PNG
OBS: Não instalei o ubuntu ainda, não sei se podia fazer com o windows e com o codeblocks...
OBS.2: Têm um problema com o codeblock que não quer ler as palavras com acentos mas nada de errado com o algoritmo.

**Comment by fsantanna** [comment]
ok

**Comment by fsantanna** [comment]
(pode fechar essa issue em "Close issue")
