### ISSUE TITLE
PRIMOS: Dá pra simplificar e tirar esse contador `cont`

### ISSUE THREAD

**Issue by fsantanna** [jaimelay/LP1#2]
https://github.com/jaimelay/LP1/blob/cd476550717a7446127b2bd1c25cb9437ff60109/exercicios%20slides/lp1-04-func_eh_primo.c#L19

**Comment by jaimelay** [comment]
Consegui, simplifiquei.

**Comment by jaimelay** [comment]
Corrigido.
