### ISSUE TITLE
Usar um ponteiro para "conta_a_ser_debitada"

### ISSUE THREAD

**Issue by fsantanna** [jaimelay/LP1#3]
https://github.com/jaimelay/LP1/blob/0e282fe5a73525f16eebb862959e024296b9ca8e/exercicios%20slides/lp1-05-ponteiros-exerc5.2.c#L13

Fazer parecido com o exercício anterior: usar um ponteiro para guardar a conta a ser usada.
Em seguida chamar compra passando esse ponteiro.

**Comment by jaimelay** [comment]
Corrigido!!!
