### ISSUE TITLE
Nessa linha, o que acontece se as contas tiverem o mesmo saldo?

### ISSUE THREAD

**Issue by fsantanna** [jaimelay/LP1#5]
https://github.com/jaimelay/LP1/blob/de8265d97e6dc5d1c53220fddbc95e69012a3646/exercicios%20slides/lp1-05-ponteiros-exerc5.2.c#L21

**Comment by jaimelay** [comment]
Eu poderia colocar qualquer uma das contas nesse caso né? Posso tirar o else if e colocar apenas o else antes ai ele sempre iria descontar da conta2 caso fossem iguais...

**Comment by fsantanna** [comment]
sim

**Comment by jaimelay** [comment]
Ok! Corrigido.
